### ISSUE TITLE
Failed to initialize NVML: GPU access blocked by the operating system

### ISSUE THREAD

**Issue by bshillingford** [Kaixhin/dockerfiles#1]
Hi, first of all, thanks for sharing these Dockerfiles. I've been trying to use your `kaixhin/cuda`, but I can't access the GPUs within the container. I'm fairly certain both the host and container are running the same CUDA versions, 7.0.28. But `nvidia-smi` always outputs `Failed to initialize NVML: GPU access blocked by the operating system`. Also `nvidia-smi -a` produces the same error, so I can't find a way to get more information about this error.  Do you have any ideas what this could be caused by?

Thanks!

Brendan

Within the docker container:

```
$ docker run -ti -v `pwd`/NVIDIA_CUDA-7.0_Samples:/cudasamples --device /dev/nvidia0:/dev/nvidia0 --device /dev/nvidia1:/dev/nvidia1 --device /dev/nvidia2:/dev/nvidia2 --device /dev/nvidia3:/dev/nvidia3 --device /dev/nvidiactl:/dev/nvidiactl --device /dev/nvidia-uvm:/dev/nvidia-uvm kaixhin/cuda /bin/bash
root@9279fc160f42:/# nvidia-smi 
Failed to initialize NVML: GPU access blocked by the operating system
root@9279fc160f42:/# /cudasamples/1_Utilities/deviceQuery/deviceQuery 
/cudasamples/1_Utilities/deviceQuery/deviceQuery Starting...
 CUDA Device Query (Runtime API) version (CUDART static linking)
cudaGetDeviceCount returned 38
-> no CUDA-capable device is detected
Result = FAIL
```

```
root@9279fc160f42:/# nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Mon_Feb_16_22:59:02_CST_2015
Cuda compilation tools, release 7.0, V7.0.27
```

On the host:

```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Mon_Feb_16_22:59:02_CST_2015
Cuda compilation tools, release 7.0, V7.0.27
$ modinfo nvidia | grep version
version:        346.47
vermagic:       3.16.0-31-generic SMP mod_unload modversions 
```

```
$ nvidia-smi
Wed Apr  8 23:47:44 2015       
+------------------------------------------------------+                       
| NVIDIA-SMI 346.47     Driver Version: 346.47         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX TIT...  On   | 0000:04:00.0     Off |                  N/A |
| 26%   28C    P8    14W / 250W |     15MiB /  6143MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX TIT...  On   | 0000:08:00.0     Off |                  N/A |
| 26%   28C    P8    14W / 250W |     15MiB /  6143MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX TIT...  On   | 0000:85:00.0     Off |                  N/A |
| 26%   29C    P8    13W / 250W |     15MiB /  6143MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX TIT...  On   | 0000:89:00.0     Off |                  N/A |
| 26%   28C    P8    14W / 250W |     15MiB /  6143MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by bshillingford** [comment]
Never mind, I fooled myself. My host has 347.47, but the version included in the CUDA installer is 347.46.

**Comment by bshillingford** [comment]
Never mind, I fooled myself. My host has 346.47, but the version included in the CUDA installer is 346.46.  Thanks!

**Comment by Kaixhin** [comment]
That's quite a subtle problem, so I'm glad you managed to solve the issue yourself. I'll be pushing an update soon which includes the CUDA driver version in the readmes so that people can check their hosts first.

**Comment by leopd** [comment]
Got this same error with a mismatch of driver versions: 346.46 to 346.72.  Make sure they match exactly!

**Comment by nh2** [comment]
Useful to know for passers-by: You cannot combine this Dockerfile with a host that has CUDA installed via one of the DEB packages from https://developer.nvidia.com/cuda-downloads, because those usually compare newer driver versions while the `.run` file contains older driver versions (e.g. `cuda_7.0.28_linux.run` still contains `346.46` when the DEBs already contain `346.82`).

To get around this, either downgrade your host driver to also use the one from the `.run` file, or build a newer container based on the DEBs - I chose to do that and built it like this:

```
# Install CUDA
docker run -ti -v $HOME/Downloads/:/cuda-installer ubuntu:14.04 bash

# Inside the container:
dpkg -i /cuda-installer/cuda-repo-ubuntu1404-7-0-local_7.0-28_amd64.deb
apt-get update
apt-get install cuda
apt-get purge cuda-repo-ubuntu1404-7-0-local
apt-get clean
rm -rf /var/lib/apt/lists/*

# Outside, commit the container
docker commit CONTAINER_ID $USER/cuda-deb:7.0.28-346.82
```

(Not using a Dockerfile here because it makes it really hard to get a file from the host into the container without it blowing up the container disk space.)

**Comment by haoyangz** [comment]
I encountered the same problem, even with the driver matched exactly...
```
Failed to initialize NVML: GPU access blocked by the operating system
```

I am using cuda-caffe7.0, which has 346.46 according to the [README.md] (https://github.com/Kaixhin/dockerfiles/tree/master/cuda-caffe/cuda_v7.0)

My host:
```
+------------------------------------------------------+
| NVIDIA-SMI 346.46     Driver Version: 346.46         |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GRID K520           Off  | 0000:00:03.0     Off |                  N/A |
| N/A   54C    P0    68W / 125W |    492MiB /  4095MiB |     98%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GRID K520           Off  | 0000:00:04.0     Off |                  N/A |
| N/A   32C    P8    17W / 125W |     11MiB /  4095MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GRID K520           Off  | 0000:00:05.0     Off |                  N/A |
| N/A   36C    P8    17W / 125W |     11MiB /  4095MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GRID K520           Off  | 0000:00:06.0     Off |                  N/A |
| N/A   32C    P8    17W / 125W |     11MiB /  4095MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      7564    C   /scripts/caffe/build/tools/caffe                89MiB |
|    0      7576    C   /scripts/caffe/build/tools/caffe               176MiB |
|    0      7590    C   /scripts/caffe/build/tools/caffe               118MiB |
|    0      7602    C   /scripts/caffe/build/tools/caffe                90MiB |
+-----------------------------------------------------------------------------+
```

**Comment by Kaixhin** [comment]
You're the first person I've seen using GRID cards instead of GeForce. Not knowing what kind of devices are produced, have you tried passing through all NVIDIA devices created under the `/dev` folder on your host?

If so, is your host running on Ubuntu or at least another Debian-based system? I haven't actually tested, so that might be a problem. In that case I'm afraid you might have to hack around and do what @nh2 suggested above.

**Comment by haoyangz** [comment]
Thanks for your reply, Kaixhin. I am using Amazon EC2 instance g2.8xlarge, which should be very popular now for cloud computing using GPU. And yes I passed all the devices.

The devices are:
```
ubuntu@ip-10-145-61-145:~$ ls /dev/nvidia* -lrt
crw-rw-rw- 1 root root 195, 255 Oct  2 13:42 /dev/nvidiactl
crw-rw-rw- 1 root root 195,   0 Oct  2 13:45 /dev/nvidia0
crw-rw-rw- 1 root root 195,   1 Oct  2 13:45 /dev/nvidia1
crw-rw-rw- 1 root root 195,   2 Oct  2 13:45 /dev/nvidia2
crw-rw-rw- 1 root root 195,   3 Oct  2 13:45 /dev/nvidia3
crw-rw-rw- 1 root root 251,   0 Oct  2 14:01 /dev/nvidia-uvm
```

The OS I am using is this [one](https://github.com/BVLC/caffe/wiki/Caffe-on-EC2-Ubuntu-14.04-Cuda-7) , which is a Ubuntu with CUDA7 and Caffe preinstalled. But I don't think it has the problem @nh2  suggested as the resulting driver version is indeed what we want (346.46). 

Another thing is that I am able to run the Caffe-Docker on GPU0, but I can't get it running the other three. I am not sure if this is related.

**Comment by Kaixhin** [comment]
I'm slightly confused - you are running Caffe in Docker on GPU0, but also get the error about failing to initialize NVML? Are you using attempting to run `kaixhin/cuda-caffe:7.0` within the [Caffe AMI](https://github.com/BVLC/caffe/wiki/Caffe-on-EC2-Ubuntu-14.04-Cuda-7)? They don't seem to follow [Amazon's instructions](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using_cluster_computing.html) on how to set up a specific version of CUDA.

Rather than using that, I'd suggest starting with a [clean version of Ubuntu](https://aws.amazon.com/marketplace/pp/B00JV9TBA6/ref=mkt_wir_Ubuntu14), and install the CUDA drivers using a run file, as explained in this [blog post](http://tleyden.github.io/blog/2014/10/25/cuda-6-dot-5-on-aws-gpu-instance-running-ubuntu-14-dot-04/). Unfortunately I don't have any experience with AMI, but @tleyden (who wrote the blog post and pioneered work in this area) might have some better ideas.

**Comment by haoyangz** [comment]
@Kaixhin  Sorry, I found that it is caused by an wrong version of my scripts which didn't actually pass in the --device that it should. After correcting for that, caffe is running greatly on all of the GPUs and I can also do `nvidia-smi` in the docker without any problem. I will delete my previous posts as they are wrong and could be misleading for others. Again I apologize...

**Comment by tengpeng** [comment]
@nh2 I tried as your guidance. Everything looks fine. However, the problem persists.

My host is a centOS, but the docker is built on Ubuntu. Does that make a difference?

**Comment by tengpeng** [comment]
```
#host 
nvidia-smi
Tue Feb  9 01:30:58 2016       
+------------------------------------------------------+                       
| NVIDIA-SMI 352.79     Driver Version: 352.79         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 750 Ti  Off  | 0000:01:00.0      On |                  N/A |
| 40%   27C    P8     1W /  38W |    274MiB /  2047MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0     10505    G   /usr/bin/X                                      91MiB |
|    0     10647    G   /usr/bin/gnome-shell                            91MiB |
|    0     12965    G   ...s-passed-by-fd --v8-snapshot-passed-by-fd    82MiB |
+-----------------------------------------------------------------------------+
```

```
#docker
root@84b9f6e2d047:~# nvidia-smi
Failed to initialize NVML: GPU access blocked by the operating system
root@fefd58c66866:~# lsmod | grep nv
nvidia               8536971  54 
drm                   349210  5 i915,drm_kms_helper,nvidia
i2c_core               40582  7 drm,i915,i2c_i801,i2c_hid,drm_kms_helper,i2c_algo_bit,nvidia
root@fefd58c66866:~# cat /proc/driver/nvidia/version
NVRM version: NVIDIA UNIX x86_64 Kernel Module  352.79  Wed Jan 13 16:17:53 PST 2016
GCC version:  gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC) 
```

**Comment by Kaixhin** [comment]
@tengpeng The OS mismatch is _almost certainly_ the problem when it comes to drivers. I am only going to support Ubuntu (but will take PRs for CentOS if anyone wants to maintain that), therefore I suggest trying [NVIDIA's project](https://github.com/NVIDIA/nvidia-docker) and letting me know so that I can update my documentation.

**Comment by tengpeng** [comment]
@Kaixhin I tried Nvidia's docker. I passed all tests and I can use the digits set. However, I fail to get the mxnet docker works.

```
sudo nvidia-docker run kaixhin/cuda-mxnet:latest nvidia-dmi
Failed to initialize NVML: Unknown Error
```

**Comment by Kaixhin** [comment]
@tengpeng Looks like you will have to build your own image using [this Dockerfile](https://github.com/Kaixhin/dockerfiles/blob/master/cuda-mxnet/cuda_v7.5/Dockerfile) for reference. It will need to start from a NVIDIA CentOS image and replace any Ubuntu-specific commands with CentOS-specific commands (like `apt-get` with `yum`).

**Comment by bshillingford** [comment]
If you want to use nvidia's thing and build off of an ubuntu image instead
of CentOS, see this dockerfile as an example:

https://github.com/NVIDIA/nvidia-docker/blob/master/ubuntu-14.04/caffe/Dockerfile

i.e. you can start from cuda:7.0-cudnn4-runtime.

**Comment by tengpeng** [comment]
@bshillingford  Thanks!

**Comment by tengpeng** [comment]
@Kaixhin Thanks! Previously, I thought I could call docker/cuda to run docker/mxnet.

**Comment by Yunrui** [comment]
@tengpeng have you fixed the issue? Please share your solution/dockerfile if you did. I am encountering the same issue. My host is cent os, with CUDA 352.79 installed. I am trying to find out how to make mxnet run on it.

**Comment by tengpeng** [comment]
@Yunrui I have successfully installed mxnet on my hard disk, rather then running a docker.  If I understand the author of the docker correctly, the docker support Ubuntu only.

**Comment by jamborta** [comment]
Hi, I have a same problem, running on a g.2xlarge EC2 host instance with ubuntu 14.04, when I run

`sudo docker run -ti --device /dev/nvidia0:/dev/nvidia0 --device /dev/nvidiactl:/dev/nvidiactl --device /dev/nvidia-uvm:/dev/nvidia-uvm kaixhin/cuda bash`

I get

`Failed to initialize NVML: GPU access blocked by the operating system`

I compared the driver, both the same:

`ubuntu@ip-172-31-43-191:~$ cat /proc/driver/nvidia/version
NVRM version: NVIDIA UNIX x86_64 Kernel Module  352.63  Sat Nov  7 21:25:42 PST 2015
GCC version:  gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.1)`

any help would be appreciated

**Comment by nh2** [comment]
@jamborta I cannot give you detail advice but NVIDIA now provides their own docker containers (https://github.com/NVIDIA/nvidia-docker) which you might want to try.

**Comment by Kaixhin** [comment]
@jamborta it appears that this driver version has problems on EC2 (see https://github.com/Kaixhin/dockerfiles/issues/7), so you'll want to either try running the container on an instance with upgraded drivers (see @nh2's solution above) or use one of NVIDIA's official images - the latter is probably easier.

**Comment by jamborta** [comment]
@nh2 @Kaixhin thanks for the replies. I would prefer to use the docker images from this repo, as I'm using the torch version. not sure what you mean by not using the latest driver, in #7 it mentions 352.63, which is the one I have.

**Comment by Kaixhin** [comment]
@jamborta I found the issues with that driver version on this [NVIDIA thread](https://devtalk.nvidia.com/default/topic/880246/cuda-7-5-unstable-on-ec2-/), which is why you will probably want to make your own Docker images using NVIDIA's official tools if you want to use EC2.

Otherwise, if you can (I don't use EC2 and don't know what's possible), you could try reinstalling the drivers and/or CUDA on the host using the [runfile](https://developer.nvidia.com/cuda-downloads).

**Comment by YIFanH** [comment]
@tengpeng  I want to use the NVIDIA Driver Version: 352.79 to do some research,but the NVIDIA of  working docker is 346.46,could you give me your  docker-cuda-container link?  Thank you for your replys.

**Comment by rangsimanketkaew** [comment]
Try updating the version of CUDA to the latest thing.
`sudo nvidia-installer --update`

**Comment by tommyjcarpenter** [comment]
Does the container need to be using the same version of cuda as the host machine?

If so, this is like an unprecedented runtime dependency that a *container* now has. Meaning, a Docker container now has specific docker hosts in which it can run on. Is there a way to even specify such a dependency? I had assumed Docker containers made no assumptions about the underlying Dockerhost.

**Comment by Kaixhin** [comment]
@tommyjcarpenter this is a kernel issue - you can find more details on the [NVIDIA Docker repo](https://github.com/NVIDIA/nvidia-docker). FYI all CUDA images in this repo now use their setup, so they are subject to whatever restrictions NVIDIA have needed.
