### ISSUE TITLE
Different Nvidia drivers for each image?

### ISSUE THREAD

**Issue by js1972** [Kaixhin/dockerfiles#12]
Is it not possible to use the same Nvidia driver versions across ALL of your images. Otherwise as it stands I need to create a completely different AWS image for each docker container I want to run, given that the docker containers only seem to work when you have the precise point version of the Nvidia drives on the host.

**Comment by Kaixhin** [comment]
Potentially, but using the latest version from a package manager is a moving target. The [recommended installation method](https://github.com/Kaixhin/dockerfiles#cuda) - the runfile - at least represents an unambiguous setup. If you can come up with reproducible steps (accounting for potential prior installations of CUDA on the host) then feel free to submit a PR.

NVIDIA provides their own solution for allowing a range of driver versions with [NVIDIA Docker](https://github.com/NVIDIA/nvidia-docker), but I will be sticking with a pure Docker solution for now (see https://github.com/Kaixhin/dockerfiles/issues/6 for more discussion).

**Comment by js1972** [comment]
Had a bit of a look at the nvidia docker but it looks like their own fork... Which doesn't interest me either....  ;-)
