### ISSUE TITLE
kaixhin/digits has a problem

### ISSUE THREAD

**Issue by DrSensor** [Kaixhin/dockerfiles#14]
In docker registry Ubuntu Core 14.04 + Pycaffe + DIGITS (CPU-only) in https://hub.docker.com/r/kaixhin/digits/

it seem libdc1394 is missing

here is log run :
/usr/local/lib/python2.7/dist-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.wtf is deprecated, use flask_wtf instead.
  .format(x=modname), ExtDeprecationWarning
libdc1394 error: Failed to initialize libdc1394
/usr/local/lib/python2.7/dist-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.socketio is deprecated, use flask_socketio instead.
  .format(x=modname), ExtDeprecationWarning
Traceback (most recent call last):
  File "/root/digits/digits-devserver", line 42, in <module>
    from digits.webapp import app, socketio, scheduler
  File "/root/digits/digits/webapp.py", line 38, in <module>
    import digits.views
  File "/root/digits/digits/views.py", line 538, in <module>
Default value for torch_root "<PATHS>" invalid:
    torch binary not found in PATH
    app.register_error_handler(code, handle_error)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1186, in register_error_handler
    self._register_error_handler(None, code_or_exception, f)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 65, in wrapper_func
    return f(self, _args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1201, in _register_error_handler
    exc_class, code = self._get_exc_class_and_code(code_or_exception)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1121, in _get_exc_class_and_code
    exc_class = default_exceptions[exc_class_or_code]
KeyError: 300
Exception KeyError: KeyError(140559450766864,) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored

**Comment by andrewssobral** [comment]
I have exactly the same error and I can't run kaixhin/digits in Docker for Windows.
in the meantime I'm using https://hub.docker.com/r/nvidia/digits/

**Comment by Kaixhin** [comment]
Just tried the last automated build and found this issue, so started a new one which seems to be fine. Please confirm with the latest build @cimenx.

**Comment by andrewssobral** [comment]
Thank you @Kaixhin 
now It works very well for me

**Comment by andrewssobral** [comment]
About libdc1394 error: Failed to initialize libdc1394
I only need to do: sudo ln /dev/null /dev/raw1394

**Comment by Kaixhin** [comment]
@andrewssobral I didn't seem to get that error (or indeed have that device under /dev). Could you please provide more information on how this affects the latest build?

**Comment by DrSensor** [comment]
Thankyou @Kaixhin although i still had 
libdc1394 error: Failed to initialize libdc1394
but its work fine now.

**Comment by andrewssobral** [comment]
Hi @cimenx try: sudo ln /dev/null /dev/raw1394
This is not the best solution, but disabling the driver the error disappears.
More info:
http://stackoverflow.com/questions/29274638/opencv-libdc1394-error-failed-to-initialize-libdc1394
http://stackoverflow.com/questions/12689304/ctypes-error-libdc1394-error-failed-to-initialize-libdc1394
Hi @Kaixhin in fact this error does not compromise the system operation. Even with libdc1394 error the DIGITS platform works fine.

**Comment by Kaixhin** [comment]
@andrewssobral Thanks for the extra detail.
