### ISSUE TITLE
Could NOT find CUDA: Found unsuitable version "7.0", but required is at least "7.5"

### ISSUE THREAD

**Issue by Teepareep** [Kaixhin/dockerfiles#16]
Getting the following error when building cudnn on the 7.0 tag release. 

[91mCMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find CUDA: Found unsuitable version "7.0", but required is at
  least "7.5" (found /usr/local/cuda)

You can see this error is generated on your automated build as well: [Docker Hub Build Log](https://hub.docker.com/r/kaixhin/cuda-torch/builds/bmuybet3rngtcdmmgvf4ky4/)

**Comment by Teepareep** [comment]
potential solution: https://github.com/soumith/cudnn.torch/issues/196

**Comment by Kaixhin** [comment]
Probably best to manually reinstall `cudnn` after `install.sh` so pushed a fix in 32f985b - will be able to check the results later in the day.
