### ISSUE TITLE
difference between cuda-mxnet and cuda-mxnet:7.0

### ISSUE THREAD

**Issue by philipskokoh** [Kaixhin/dockerfiles#19]
What is the difference between cuda-mxnet and cuda-mxnet:7.0 image?
Mxnet python demo works properly on `cuda-mxnet:7.0`, but it fails on `cuda-mxnet`.

Run demo in cuda-mxnet:7.0 

```
nvidia-docker run -it --rm kaixhin/cuda-mxnet:7.0 python example/image-classification/train_mnist.py --network lenet --gpus 0
```

This command returns no errors.

Run demo in cuda-mxnet 

```
nvidia-docker run -it --rm kaixhin/cuda-mxnet python example/image-classification/train_mnist.py --network lenet --gpus 0
```

This one returns error. These are the error messages:

```
Archive:  mnist.zip
  inflating: t10k-images-idx3-ubyte  
  inflating: t10k-labels-idx1-ubyte  
  inflating: train-images-idx3-ubyte  
  inflating: train-labels-idx1-ubyte  
[06:07:46] src/io/iter_mnist.cc:94: MNISTIter: load 60000 images, shuffle=1, shape=(128,1,28,28)
[06:07:46] src/io/iter_mnist.cc:94: MNISTIter: load 10000 images, shuffle=1, shape=(128,1,28,28)
2016-10-03 06:07:46,795 Node[0] Start training with [gpu(0)]
[06:10:16] /root/mxnet/dmlc-core/include/dmlc/logging.h:235: [06:10:16] /root/mxnet/mshadow/mshadow/./././dot_engine-inl.h:524: Check failed: (err) == (CUBLAS_STATUS_SUCCESS) Cublas: Sgemm fail
[06:10:16] /root/mxnet/dmlc-core/include/dmlc/logging.h:235: [06:10:16] src/engine/./threaded_engine.h:306: [06:10:16] /root/mxnet/mshadow/mshadow/./././dot_engine-inl.h:524: Check failed: (err) == (CUBLAS_STATUS_SUCCESS) Cublas: Sgemm fail
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
terminate called after throwing an instance of 'dmlc::Error'
  what():  [06:10:16] src/engine/./threaded_engine.h:306: [06:10:16] /root/mxnet/mshadow/mshadow/./././dot_engine-inl.h:524: Check failed: (err) == (CUBLAS_STATUS_SUCCESS) Cublas: Sgemm fail
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
```

**Comment by Kaixhin** [comment]
First as a sanity check please try another CUDA 7.5 image - for instance I know that `kaixhin/cuda-torch` works, so after running `nvidia-docker run -it --rm kaixhin/cuda-torch th` you can run the following:

``` lua
require 'cutorch'
os.exit()
```

I ran `diff` on the Dockerfiles - the only difference is the version of CUDA (7.5 vs. 7.0) and cuDNN (5 vs 4). I'm pretty sure the MXNet should support cuDNN 5, but that's the only problem. I'd suggest cloning this repo, changing [this line](https://github.com/Kaixhin/dockerfiles/blob/master/cuda-mxnet/cuda_v7.5/Dockerfile#L2) from `cuda:7.5-cudnn5-devel` to `cuda:7.5-cudnn4-devel`, building it yourself and seeing if that works.

**Comment by philipskokoh** [comment]
`kaixhin/cuda-torch` works fine.

Changing to `cuda:7.5-cudnn4-devel` gives the same error. Looks like mxnet has some problems with CUDA 7.5.
Do you think this is a mxnet issue and I have to post the issue there?

**Comment by Kaixhin** [comment]
There's a small chance that it's an issue with `nvidia-docker`, but I think the best way forward is to post this issue on the MXNet repo and refer to this one, seeing as there's no difference in the Dockerfiles beyond CUDA versions.

**Comment by philipskokoh** [comment]
Just saw your `kaixhin/cuda-mxnet:8.0`. I test the same command on this docker image. It works!
I think the problem should be inside `nvidia/cuda:7.5-cudnn5-devel` docker image.

**Comment by philipskokoh** [comment]
I suggest to remove `kaixhin/cuda-mxnet:7.5` and set the latest to `kaixhin/cuda-mxnet:8.0`
