### ISSUE TITLE
cannot find cuda samples script

### ISSUE THREAD

**Issue by xianlin** [Kaixhin/dockerfiles#2]
If using the official cuda installer, I can find `cuda-install-samples-7.0.sh`.
http://docs.nvidia.com/cuda/cuda-samples/index.html#getting-cuda-samples

However, after building using your dockerfile, I cannot find this script. 

How to include the cuda samples in the docker image? Because I want to test the cuda with GPU by using `deviceQuery` script.

**Comment by Kaixhin** [comment]
As the image is intended for "production", the samples were not installed. You will need to install the samples via the installer yourself. The steps are as below:

```
wget http://developer.download.nvidia.com/compute/cuda/7_0/Prod/local_installers/cuda_7.0.28_linux.run
chmod +x cuda_*_linux.run
./cuda_*_linux.run -extract=`pwd`
./cuda-samples-linux-*.run -noprompt
```

Please note that you may need to install other packages in order to compile some of the CUDA samples.
