### ISSUE TITLE
Problem running digits server: 'No module named digits'

### ISSUE THREAD

**Issue by pogopaule** [Kaixhin/dockerfiles#21]
Running `docker run --rm -p 8080:5000 kaixhin/digits` gives me `/usr/bin/python: No module named digits`.

Running

```
docker run -it --rm kaixhin/digits bash
cd /root/digits/
pip install -r requirements.txt
/root/digits/digits-devserver
```

fixes the problem and the digits server start.
So is there a problem with the digits image?

**Comment by vuhailuyen1991** [comment]
Same issue here.
