### ISSUE TITLE
Cuda-Digits:8.0 with Multi GPU

### ISSUE THREAD

**Issue by ghost** [Kaixhin/dockerfiles#23]
I am getting error while training in digits:

"ERROR: USE_NCCL := 1 must be specified for multi-GPU"

I guess caffe should be compiled with USE_NCCL := 1.

How can I do this? I am new to docker issues..

**Comment by Kaixhin** [comment]
I've added NCCL into the image but Caffe doesn't seem to be picking it up - I will investigate again in a few days time.

**Comment by Kaixhin** [comment]
The [latest build](https://hub.docker.com/r/kaixhin/cuda-digits/builds/b6isk38gewmvqnkpkzugbjq/) of `kaixhin/cuda-digits:8.0` now is building with NCCL. `7.5` and the corresponding `kaixhin/cuda-caffe` images will also include NCCL the next time they are built.

**Comment by ten2net** [comment]
![cuda-digits-ui-bug](https://cloud.githubusercontent.com/assets/1018417/20822284/560b0862-b884-11e6-87cb-22d757ca8e01.png)
* maybe json parse error. UI display raw json.
{[ jobs = (jc.model_jobs | filter:search_text | sort_with_empty_at_end:this:jc.storage.show_groups); '' ]}

* ex:
{[enabled = any_selected();'']} {[group_enabled = jc.storage.show_groups && enabled;'']}

**Comment by ten2net** [comment]
not support multi-GPU :[ERROR] Train Caffe Model: USE_NCCL := 1 must be specified for multi-GPU

**Comment by ten2net** [comment]
when use 1 GPU, occupt [ERROR] Train Caffe Model: Check failed: error == cudaSuccess (8 vs. 0) invalid device function

**Comment by chengsq** [comment]
@ten2net how to fix problem with  {[ jobs = (jc.model_jobs | filter:search_text | sort_with_empty_at_end:this:jc.storage.show_groups); '' ]}

ex:
{[enabled = any_selected();'']} {[group_enabled = jc.storage.show_groups && enabled;'']}
