### ISSUE TITLE
cuda-theano:7.5 import error

### ISSUE THREAD

**Issue by hypercost** [Kaixhin/dockerfiles#24]
I run this cuda-theano image use the command:

```
sudo nvidia-docker run -it --name theano kaixhin/cuda-theano:7.5 /bin/bash
```

In the theano container, I test the gpu theano and I have the error:

```
root@cd170ec8e8f9:~# python -c "import theano; theano.test()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/theano/__init__.py", line 79, in <module>
    from theano.scan_module import (scan, map, reduce, foldl, foldr, clone,
  File "/usr/local/lib/python2.7/dist-packages/theano/scan_module/__init__.py", line 41, in <module>
    from theano.scan_module import scan_opt
  File "/usr/local/lib/python2.7/dist-packages/theano/scan_module/scan_opt.py", line 71, in <module>
    from theano.scan_module import scan_op
  File "/usr/local/lib/python2.7/dist-packages/theano/scan_module/scan_op.py", line 58, in <module>
    from six import iteritems, integer_types, raise_from
ImportError: cannot import name raise_from
```

I'm sure nvidia-docker works well on my computer.
May I have any help?

**Comment by Mr-Grieves** [comment]
Experiencing the same issue here, even though this used to be working fine.

Any suggestions?

**Comment by Kaixhin** [comment]
I'm not sure how this would have broken since. I don't have time to investigate myself, but a good place to start investigating would be to build the original [Dockerfile](https://github.com/Kaixhin/dockerfiles/blob/master/cuda-theano/cuda_v7.5/Dockerfile).

**Comment by Mr-Grieves** [comment]
Ya I don't understand how this showed up out of the blue...

For the time being, it seems I can get around by doing a hard reinstall of `six`:
```
rm -rf /usr/local/lib/python2.7/dist-packages/*six*
rm -rf /usr/lib/python2.7/dist-packages/*six*
pip install --upgrade six
```
