### ISSUE TITLE
cuda-mxnet build failed for the past 2 months

### ISSUE THREAD

**Issue by philipskokoh** [Kaixhin/dockerfiles#28]
From this page, it seems that the dockerfile fails to compile recent mxnet updates:
https://hub.docker.com/r/kaixhin/cuda-mxnet/builds/

**Comment by Kaixhin** [comment]
Not sure exactly what is causing the error, but it builds fine on my machine, and even on the Docker Hub [(apparently)](https://hub.docker.com/r/kaixhin/cuda-mxnet/builds/bkdbvrnayfm7juhbqabrw89/]). Seems like something is going wrong when pushing the image, but we will have to wait for Docker to respond: https://github.com/docker/hub-feedback/issues/547
