### ISSUE TITLE
cuda-torch/cuda_v8.0 fails

### ISSUE THREAD

**Issue by jklappenbach** [Kaixhin/dockerfiles#29]
Two warnings are being regarded as errors by the compiler when compiling THC.  Perhaps flags allowing these warnings to proceed might help.

Scanning dependencies of target THC
[ 82%] [ 83%] Building CXX object lib/THC/CMakeFiles/THC.dir/THCCachingAllocator.cpp.o
[ 84%] [ 86%] [ 88%] [ 88%] [ 89%] [ 90%] Building CXX object lib/THC/CMakeFiles/THC.dir/THCCachingHostAllocator.cpp.o
Building C object lib/THC/CMakeFiles/THC.dir/THCStorageCopy.c.o
Building C object lib/THC/CMakeFiles/THC.dir/THCTensorCopy.c.o
Building C object lib/THC/CMakeFiles/THC.dir/THCTensor.c.o
Building C object lib/THC/CMakeFiles/THC.dir/THCGeneral.c.o
Building CXX object lib/THC/CMakeFiles/THC.dir/THCStream.cpp.o
Building CXX object lib/THC/CMakeFiles/THC.dir/THCTensorRandom.cpp.o
In file included from generic/THCTensor.c:1:0,
                 from /tmp/luarocks_cutorch-scm-1-2857/cutorch/lib/THC/THCGenerateAllTypes.h:17,
                 from /tmp/luarocks_cutorch-scm-1-2857/cutorch/lib/THC/THCTensor.c:7:
/tmp/luarocks_cutorch-scm-1-2857/cutorch/lib/THC/generic/THCTensor.c: In function 'THCudaByteTensor_newView':
/tmp/luarocks_cutorch-scm-1-2857/cutorch/lib/THC/generic/THCTensor.c:231:3: error: implicit declaration of function 'THLongStorage_newInferSize' [-Werror=implicit-function-declaration]
   THLongStorage *inferred_size = THLongStorage_newInferSize(size, numel);
   ^
/tmp/luarocks_cutorch-scm-1-2857/cutorch/lib/THC/generic/THCTensor.c:231:34: warning: initialization makes pointer from integer without a cast [enabled by default]
   THLongStorage *inferred_size = THLongStorage_newInferSize(size, numel);
                                  ^
In file included from generic/THCTensor.c:1:0,
                 from /tmp/luarocks_cutorch-scm-1-2857/cutorch/lib/THC/THCGenerateAllTypes.h:18,
                 from /tmp/luarocks_cutorch-scm-1-2857/cutorch/lib/THC/THCTensor.c:7:
/tmp/luarocks_cutorch-scm-1-2857/cutorch/lib/THC/generic/THCTensor.c: In function 'THCudaCharTensor_newView':
/tmp/luarocks_cutorch-scm-1-2857/cutorch/lib/THC/generic/THCTensor.c:231:34: warning: initialization makes pointer from integer without a cast [enabled by default]
   THLongStorage *inferred_size = THLongStorage_newInferSize(size, numel);
                                  ^
In file included from generic/THCTensor.c:1:0,
                 from /tmp/luarocks_cutorch-scm-1-2857/cutorch/lib/THC/THCGenerateAllTypes.h:19,
                 from /tmp/luarocks_cutorch-scm-1-2857/cutorch/lib/THC/THCTensor.c:7:
/tmp/luarocks_cutorch-scm-1-2857/cutorch/lib/THC/generic/THCTensor.c: In function 'THCudaShortTensor_newView':
/tmp/luarocks_cutorch-scm-1-2857/cutorch/lib/THC/generic/THCTensor.c:231:34: warning: initialization makes pointer from integer without a cast [enabled by default]
   THLongStorage *inferred_size = THLongStorage_newInferSize(size, numel);
                                  ^
In file included from generic/THCTensor.c:1:0,
                 from /tmp/luarocks_cutorch-scm-1-2857/cutorch/lib/THC/THCGenerateAllTypes.h:20,
                 from /tmp/luarocks_cutorch-scm-1-2857/cutorch/lib/THC/THCTensor.c:7:
/tmp/luarocks_cutorch-scm-1-2857/cutorch/lib/THC/generic/THCTensor.c: In function 'THCudaIntTensor_newView':
/tmp/luarocks_cutorch-scm-1-2857/cutorch/lib/THC/generic/THCTensor.c:231:34: warning: initialization makes pointer from integer without a cast [enabled by default]
   THLongStorage *inferred_size = THLongStorage_newInferSize(size, numel);
                                  ^
In file included from generic/THCTensor.c:1:0,
                 from /tmp/luarocks_cutorch-scm-1-2857/cutorch/lib/THC/THCGenerateAllTypes.h:21,
                 from /tmp/luarocks_cutorch-scm-1-2857/cutorch/lib/THC/THCTensor.c:7:
/tmp/luarocks_cutorch-scm-1-2857/cutorch/lib/THC/generic/THCTensor.c: In function 'THCudaLongTensor_newView':
/tmp/luarocks_cutorch-scm-1-2857/cutorch/lib/THC/generic/THCTensor.c:231:34: warning: initialization makes pointer from integer without a cast [enabled by default]
   THLongStorage *inferred_size = THLongStorage_newInferSize(size, numel);
                                  ^
In file included from generic/THCTensor.c:1:0,
                 from /tmp/luarocks_cutorch-scm-1-2857/cutorch/lib/THC/THCGenerateAllTypes.h:22,
                 from /tmp/luarocks_cutorch-scm-1-2857/cutorch/lib/THC/THCTensor.c:7:
/tmp/luarocks_cutorch-scm-1-2857/cutorch/lib/THC/generic/THCTensor.c: In function 'THCudaHalfTensor_newView':
/tmp/luarocks_cutorch-scm-1-2857/cutorch/lib/THC/generic/THCTensor.c:231:34: warning: initialization makes pointer from integer without a cast [enabled by default]
   THLongStorage *inferred_size = THLongStorage_newInferSize(size, numel);
                                  ^
In file included from generic/THCTensor.c:1:0,
                 from /tmp/luarocks_cutorch-scm-1-2857/cutorch/lib/THC/THCGenerateAllTypes.h:23,
                 from /tmp/luarocks_cutorch-scm-1-2857/cutorch/lib/THC/THCTensor.c:7:
/tmp/luarocks_cutorch-scm-1-2857/cutorch/lib/THC/generic/THCTensor.c: In function 'THCudaTensor_newView':
/tmp/luarocks_cutorch-scm-1-2857/cutorch/lib/THC/generic/THCTensor.c:231:34: warning: initialization makes pointer from integer without a cast [enabled by default]
   THLongStorage *inferred_size = THLongStorage_newInferSize(size, numel);
                                  ^
In file included from generic/THCTensor.c:1:0,
                 from /tmp/luarocks_cutorch-scm-1-2857/cutorch/lib/THC/THCGenerateAllTypes.h:24,
                 from /tmp/luarocks_cutorch-scm-1-2857/cutorch/lib/THC/THCTensor.c:7:
/tmp/luarocks_cutorch-scm-1-2857/cutorch/lib/THC/generic/THCTensor.c: In function 'THCudaDoubleTensor_newView':
/tmp/luarocks_cutorch-scm-1-2857/cutorch/lib/THC/generic/THCTensor.c:231:34: warning: initialization makes pointer from integer without a cast [enabled by default]
   THLongStorage *inferred_size = THLongStorage_newInferSize(size, numel);
                                  ^
cc1: some warnings being treated as errors
make[2]: *** [lib/THC/CMakeFiles/THC.dir/THCTensor.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [lib/THC/CMakeFiles/THC.dir/all] Error 2
make: *** [all] Error 2

Error: Build error: Failed building.
Installing https://raw.githubusercontent.com/torch/rocks/master/cutorch-scm-1.rockspec...
Using https://raw.githubusercontent.com/torch/rocks/master/cutorch-scm-1.rockspec... switching to 'build' mode
cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/root/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/root/torch/install/lib/luarocks/rocks/cutorch/scm-1" && make -j$(getconf _NPROCESSORS_ONLN) install

The command '/bin/sh -c luarocks install cutorch &&   luarocks install cunn &&   luarocks install cudnn' returned a non-zero code: 1

**Comment by Kaixhin** [comment]
I'm not sure why this was happening, but I've now fixed a problem with a parent dependency image (`kaixhin/cuda-torch-deps:8.0`) and built `kaixhin/cuda-torch:8.0` successfully from that on a local machine, so this should be resolved.
