### ISSUE TITLE
cuda-ssh does not allow root logins on cuda_v8.0 tag

### ISSUE THREAD

**Issue by acerjanic** [Kaixhin/dockerfiles#30]
The cuda-ssh dockerfile appears to have an error where sshd_config is modified. Right now root logins remain prohibited when the container is built on the cuda_v8.0. 

The line: 
`  # Allow root login with password
  sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
`

should be the following (I think).

`  # Allow root login with password
  sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \`

Rebuilding the container from the modified dockerfile allowed root login via ssh for me.

**Comment by Kaixhin** [comment]
Thanks for reporting and providing a fix - I've just set off a new build for this specific image, so that should be done soon. Would you kindly be able to check if this affects the other versions of CUDA and the non-CUDA SSH image?
