### ISSUE TITLE
an env question of cuda-torch

### ISSUE THREAD

**Issue by BDon-Tan** [Kaixhin/dockerfiles#31]
I pulled the container of cuda-torch by the instruction. However, I find that we don't have /root/.luarocks/config-5.1.lua/ and /usr/local/share/lua/ exists. 
Why do we need to set LUA_PATH and LUA_CPATH with /root/.luarocks/config-5.1.lua/ and /usr/local/share/lua/
![image](https://cloud.githubusercontent.com/assets/12856975/25366671/d5096204-29a3-11e7-8f8f-6797ccc07e96.png)

![image](https://cloud.githubusercontent.com/assets/12856975/25366648/a7d554b4-29a3-11e7-99aa-caf558e469ec.png)

**Comment by Kaixhin** [comment]
I don't know that much about Lua, so I just made sure that all the exports in `/root/torch/install/bin/torch-activate` were copied over. I just checked and the exports haven't changed, so it should be, at worst, safe to keep them as-is.
