### ISSUE TITLE
digits cpu image-add support for data & jobs volumes/host persistence

### ISSUE THREAD

**Issue by rquintino** [Kaixhin/dockerfiles#33]
Hi, would be cool to add support like in the default nvidia digits gpu dockerfile:

[https://gitlab.com/nvidia/digits/blob/master/5.0/Dockerfile](https://gitlab.com/nvidia/digits/blob/master/5.0/Dockerfile)

VOLUME /data
VOLUME /jobs

ENV DIGITS_JOBS_DIR=/jobs
ENV DIGITS_LOGFILE_FILENAME=/jobs/digits.log

great work! regards
RQ

**Comment by Kaixhin** [comment]
Looks good, thanks!

Closed by https://github.com/Kaixhin/dockerfiles/pull/34.
