### ISSUE TITLE
docker: Error response from daemon: manifest for kaixhin/cuda-torch:latest not found.

### ISSUE THREAD

**Issue by Jayhello** [Kaixhin/dockerfiles#39]
I usr [crnn]( https://github.com/bgshih/crnn/blob/master/Dockerfile ) but it shows the above error.

Then i use `nvidia-docker run -it kaixhin/cuda-torch`  this, it also show:
```

Unable to find image 'kaixhin/cuda-torch:latest' locally
docker: Error response from daemon: manifest for kaixhin/cuda-torch:latest not found.
See 'docker run --help'

```

My machine is ubuntu16.04.

**Comment by Kaixhin** [comment]
There's no `latest` tag, only [`7.5` and `8.0`](https://github.com/pytorch/pytorch/pull/4681), which corresponds to CUDA versions. Therefore the Dockerfile needs to be updated to point to one of these specifically.
