### ISSUE TITLE
Spearmint script?

### ISSUE THREAD

**Issue by Kaixhin** [Kaixhin/dockerfiles#4]
Spearmint requires [several steps to get started](https://github.com/HIPS/Spearmint#setting-up-spearmint); this could probably be reduced to make things smoother (for [FGLab](https://github.com/Kaixhin/FGMachine/tree/master/examples/Bayesian-Optimisation) for example). Additionally it should be reasonably easy to have a separate [MongoDB container](https://hub.docker.com/_/mongo/). The disadvantage is keeping Spearmint documentation within this project, which requires keeping up to date with any potential API changes.

Pinging @gngdb for feedback on how to approach this.

**Comment by gngdb** [comment]
Seems like the nicest way for this to work would be a container with an ONBUILD command that adds in the config json, then an interface to communicate suggestions and results between the host; or another container running Spearmint. Then, when running an experiment you could just put a one line Dockerfile in the directory with the config.json. Although, then the script running the experiment wouldn't be compatible with Spearmint's default interface; or to use the container in this way you'd need to have another script that calls the first expecting the traditional spearmint-like interface and handles communication to the container. That would probably be best for making containers with experiments communicating to spearmint containers.
