### ISSUE TITLE
"torch" dockerfile lacks iTorch

### ISSUE THREAD

**Issue by arbitrary-dev** [Kaixhin/dockerfiles#41]
>README.md
>... (including iTorch)

But:
```
root@f34323292132:~/torch# itorch notebook
bash: itorch: command not found
```

**Comment by Kaixhin** [comment]
This has now been fixed for the `torch` image, and I will push new builds for `cuda-torch` soon. Note that only `itorch` (console mode) is supported, not `itorch notebook`.

**Comment by arbitrary-dev** [comment]
```
Dockerfile
...
# Install Jupyter Notebook for iTorch
```
This should be fixed too, probably.

Also, would be nice to mention this in README.md

**Comment by Kaixhin** [comment]
Sorry, forgot that notebooks are supported, the container just needs to have the appropriate port open. Just checked it, works fine.
