### ISSUE TITLE
Updated DIGITS CPU image?

### ISSUE THREAD

**Issue by kmader** [Kaixhin/dockerfiles#43]
Can you push an update to DIGITS (https://hub.docker.com/r/kaixhin/digits/) to 6.0 or is there a reason you are sticking at 5?

**Comment by Kaixhin** [comment]
No reason, but I'm not actively maintaining this repo. As part of the update I've moved to Ubuntu 16.04 to fix a bunch of problems between 14.04's Python and other packages.

**Comment by kmader** [comment]
great! thanks, I've been working to get Digits in Binder and moving up to 6.1.1 makes it a lot nicer: https://github.com/4Quant/digits-docker-binder
