### ISSUE TITLE
Latest CUDA 7.5

### ISSUE THREAD

**Issue by neocxi** [Kaixhin/dockerfiles#7]
It seems like the latest version of CUDA 7.5 (352.63), which fixes a critical bug on ec2, is only available .deb installer but not in .run installers. Hence the dockerfile in this repo will not install the latest version of CUDA 7.5.

I'm not sure if this is an "issue" that should be fixed but I think it's worth pointing out in case someone elses run into the same situation.

**Comment by Kaixhin** [comment]
Thanks for reporting - I'll leave this issue open for now. I've made the decision to stick with the latest .run installer to at least have a consistent driver to specify, but once https://github.com/NVIDIA/nvidia-docker/issues/7 is finished I'll be deprecating `kaixhin/cuda` and using different drivers won't be an issue.
