### ISSUE TITLE
CNMeM support?

### ISSUE THREAD

**Issue by carlthome** [Kaixhin/dockerfiles#8]
Will there be CNMeM support in the Lasagne image eventually?

**Comment by Kaixhin** [comment]
Never heard of it before - do I just need to set [this flag](http://deeplearning.net/software/theano/library/config.html#config.config.lib.cnmem) to 1 in the Theano image? If so then that should be simple enough.

**Comment by carlthome** [comment]
Yes, please. Thanks.

**Comment by Kaixhin** [comment]
`kaixhin/cuda-lasagne` should hopefully be built with CNMeM now.
